#---------------------------------------------------------------------------------------
#
# Logging Configuration File - Use this file to change logging levels
#
#---------------------------------------------------------------------------------------

  default: error
