- platform: mqtt
  state_topic: "owntracks/mallika/mallika"
  name: "Mallika's iPhone Battery"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"

- platform: mqtt
  state_topic: "owntracks/suresh/suresh"
  name: "Suresh's iPhone Battery"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"

- platform: mqtt
  state_topic: "owntracks/srinika/Srinika"
  name: "Srinika's iPhone Battery"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"

- platform: mqtt
  state_topic: "owntracks/hasika/Hasika"
  name: "Hasika's iPhone Battery"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"

