- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: memory_free
    - type: processor_use
    - type: ipv4_address
      arg: wlan0
    - type: last_boot
    - type: since_last_boot
