- alias: Animate Master Bedroom Colors
  trigger:
    platform: time
    seconds: '/5'
  condition:
    - condition: state
      entity_id: input_boolean.animate_upstairs_lights
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: group.master_bedroom_lights
        transition: 5
        brightness: 255
        color_temp: 366
      data_template:
        rgb_color: ['{{ "{0:d}".format(range(0, 255)|random) }}' , '{{ "{0:d}".format(range(0, 255)|random) }}', '{{ "{0:d}".format(range(0, 255)|random) }}']

- alias: Restore Masterbedroom Lights
  trigger:
    platform: state
    entity_id: input_boolean.animate_upstairs_lights
    to: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: group.master_bedroom_lights
        transition: 5
        rgb_color: [224,175,102]
        brightness: 10
        color_temp: 366

- alias: Animate Familyroom Colors
  trigger:
    platform: time
    seconds: '/5'
  condition:
    - condition: state
      entity_id: input_boolean.animate_downstairs_lights
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: group.family_room_lights
        transition: 5
        brightness: 255
        color_temp: 366
      data_template:
        rgb_color: ['{{ "{0:d}".format(range(0, 255)|random) }}' , '{{ "{0:d}".format(range(0, 255)|random) }}', '{{ "{0:d}".format(range(0, 255)|random) }}']
        
- alias: Restore Familyroom Lights
  trigger:
    platform: state
    entity_id: input_boolean.animate_downstairs_lights
    to: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: group.family_room_lights
        transition: 5
        rgb_color: [255, 251, 245]
        brightness: 255
        color_temp: 162
