##############################################################################################################################
# This script notifies Home Security System state changes. 
# Everytime someone changes the Alarm mode, it goes to unknown/pending state first and then goes to the desired state
# I've put conditions not to notify and announce the intermediate "pending/unknown" state
##############################################################################################################################
- alias: Notify Home Security Status
  trigger:
    platform: state
    entity_id: alarm_control_panel.simplisafe
  action:
    - service: ifttt.trigger
      data_template:
        event: "Smart Home"
        value1: >
            {% if trigger.to_state.state | lower == "disarmed" %}
                Attention!: Your Home Security System is turned OFF. All sensors are completely disabled.
            {% elif trigger.to_state.state | lower == "armed_home" %}
                Your Home Security System is now set to Home mode. Your home is now secured.
            {% elif trigger.to_state.state | lower == "armed_away" %}
                Your Home Security System is now set to Away mode. All the motion sensors are fully activated.
            {% elif trigger.to_state.state | lower == "triggered" %}
                Attention!: Your Home Security System is triggered!" It has been notified to the authorities. Police and help is on the way!
            {% endif %}
        value2: ""
    - service: mqtt.publish
      data_template:
        topic: !secret mqtt_announcement_topic
        payload: >
            {% if trigger.to_state.state == "disarmed" %}
                Attention!: Your Home Security System is turned OFF. All sensors are completely disabled.
            {% elif trigger.to_state.state == "armed_home" %}
                Your Home Security System is now set to Home mode. Your home is now secured.
            {% elif trigger.to_state.state == "armed_away" %}
                Your Home Security System is now set to Away mode. All the motion sensors are fully activated.
            {% elif trigger.to_state.state == "triggered" %}
                Attention!: Your Home Security System is triggered!" It has been notified to the authorities. Police and help is on the way!.
            {% endif %}
