- alias: Notify Home Security Status
  trigger:
    platform: state
    entity_id: alarm_control_panel.simplisafe
  action:
    - service: ifttt.trigger
      data_template:
        event: "Smart Home"
        value1: >
          "Home Security System state just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}!"
        value2: ""  
    - service: mqtt.publish
      data_template:
        topic: !secret mqtt_announcement_topic
        payload: >
          "Home Security System state just changed from '{{ trigger.from_state.state }}' to '{{ trigger.to_state.state }}'."
